POS_ABBREVIATIONS = {
    "pos": "part of speech",
    "prep.": "preposition",
    "n.": "noun",
    "a.": "adjective",
    "v. t.": "verb transitive",
    "adv.": "adverb",
    "pl.": "plural",
    "p. p.": "past participle",
    "imp. & p. p.": "imperative and past participle",
    "p. pr. & vb. n.": "present participle and verbal noun",
    "v.": "verb",
    "v. i.": "verb intransitive",
    "n. pl.": "noun plural",
    "adv. & a.": "adverb and adjective",
    "superl.": "superlative",
    "v. t. & i.": "verb transitive and intransitive",
    "p. a.": "predicative adjective",
    "p. p. & a.": "past participle and adjective",
    "a & n.": "adjective and noun",
    "a. & adv.": "adjective and adverb",
    "interj. & adv.": "interjection and adverb",
    "n. & a.": "noun and adjective",
    "imp.": "imperative",
    "adv. or prep.": "adverb or preposition",
    "v. i. & t.": "verb intransitive and transitive",
    "sing.": "singular",
    "n., a., & v.": "noun, adjective, and verb",
    "v./t.": "verb transitive",
    "p.a.": "participle adjective",
    "adj.": "adjective",
    "n. sing. & pl.": "noun singular and plural",
    "prep. & adv.": "preposition and adverb",
    "adv. & conj.": "adverb and conjunction",
    "n. fem.": "noun feminine",
    "conj.": "conjunction",
    "pref.": "prefix",
    "n. & v.": "noun and verb",
    "interj.": "interjection",
    "pron.": "pronoun",
    "compar.": "comparative",
    "n. / v. t. & i.": "noun, verb transitive and intransitive",
    "3d sing. pr.": "third person singular present",
    "p. pr.": "present participle",
    "v. & n.": "verb and noun",
    "imp. &. p. p.": "imperative and past participle",
    "n.pl.": "noun plural",
    "v.t.": "verb transitive",
    "v.i.": "verb intransitive",
    "n. sing.": "noun singular",
    "p. pr. vb. n.": "present participle verbal noun",
    "v. t. / v. i.": "verb transitive or intransitive",
    "suffix.": "suffix",
    "n. Chem.": "noun, chemistry-related",
    "adv.": "adverb",
    "comp.": "comparative",
    "n. & v. t.": "noun and verb transitive",
    "v. imperative.": "verb imperative",
    "pron., a., & adv.": "pronoun, adjective, and adverb",
    "inf.": "infinitive",
    "dat. & obj.": "dative and objective",
    "n. & interj.": "noun and interjection",
    "obs.": "obsolete",
    "def. art.": "definite article",
    "a.": "adjective",
    "v. r.": "verb reflexive",
    "p. pl.": "past participle plural",
    "interj., adv., & n.": "interjection, adverb, and noun",
    "e. t.": "etymological term",
    "imp. p. p.": "imperative past participle",
    "3d pers. sing. pres.": "third person singular present",
    "n.sing & pl.": "noun singular and plural",
    "n. collect. & pl.": "collective noun and plural",
    "pres. indic. sing., 1st & 3d pers.": "present indicative singular, first and third person",
    "superl": "superlative",
    "obj.": "objective case",
    "indic. present": "indicative present",
    "p. pr. & vb/ n.": "present participle and verbal noun",
    "n. masc.": "noun masculine",
    "n. fem.": "noun feminine",
    "imperative sing.": "imperative singular",
    "Archaic imp. & p. p.": "archaic imperative and past participle",
    "adv., prep., & conj.": "adverb, preposition, and conjunction",
    "pron., a., conj., & adv.": "pronoun, adjective, conjunction, and adverb",
    "n. Chem.": "noun chemistry-related",
    "pers. pron.": "personal pronoun",
    "subj. 3d pers. sing.": "subjunctive third person singular",
    "Archaic": "archaic form",
    "adv. / a.": "adverb or adjective",
}
