# Generated by Django 4.1.3 on 2025-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group9', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.PositiveIntegerField(verbose_name='شناسه کاربر'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='questions',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.PositiveIntegerField(verbose_name='شناسه کاربر'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.JSONField(default=list, verbose_name='شناسه سوالات'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='questions',
            field=models.JSONField(default=list, verbose_name='شناسه سوالات'),
        ),
    ]
